'use strict';

exports.BattleLearnsets = {
combzaprior: {learnset: {
		attract: ["7M"],
		aurasphere: ["7E"],
		brickbreak: ["7L23", "7M"],
		bulkup: ["7M", "7L30"],
		captivate: ["7E"],
		calmmind: ["7M"],
		charge: ["7L6"],
		chargebeam: ["7L18", "7M"],
		confide: ["7M"],
		counter: ["7E"],
		crosschop: ["7L42"],
		cut: ["7M"],
		dazzlinggleam: ["7L29", "7M"],
		darkpulse: ["7M"],
		electricterrain: ["7L1", "7L43"],
		electroball: ["7L1", "7L30"],
		endeavor: ["7L1"],
		endure: ["7L1"],
		facade: ["7M"],
		fireblast: ["7M", "7L49"],
		flameburst: ["7E"],
		flamecharge: ["7M"],
		flamethrower: ["7M"],
		focusblast: ["7M", "7L51"],
		focuspunch: ["7L34"],
		forcepalm: ["7E"],
		frustration: ["7M"],
		grassknot: ["7M"],
		gigaimpact: ["7M"],
		hiddenpower: ["7M"],
		hyperbeam: ["7M"],
		manipulatingblow: ["7L1", "7E"],
		protect: ["7M"],
		quickspark: ["7L19"],
		raindance: ["7M"],
		rest: ["7M"],
		retaliate: ["7L6"],
		return: ["7M"],
		revenge: ["7L1"],
		reversal: ["7L21"],
		rocksmash: ["7L6"],
		round: ["7M"],
		shockwave: ["7L21"],
		sleeptalk: ["7M"],
		snore: ["7M"],
		spark: ["7L15"],
		substitute: ["7M"],
		thief: ["7E"],
		thunder: ["7M", "7L43"],
		thunderpunch: ["7L1"],
		thundershock: ["7L4"],
		thunderwave: ["7M", "7L1"],
		thunderbolt: ["7M", "7L30"],
		toxic: ["7M"],
		voltswitch: ["7M", "7L20"],
		waterpulse: ["7E"],
		wildcharge: ["7M"],
		zapcannon: ["7L61"],
	}},
  };
